apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-devops-api
  namespace: ai-devops

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ai-devops-api

  template:
    metadata:
      labels:
        app: ai-devops-api

    spec:
      containers:
        - name: api

          image: 678882708618.dkr.ecr.ap-south-1.amazonaws.com/ai-devops-api:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-devops-secrets
                  key: GEMINI_API_KEY
            - name: DASHBOARD_NAMESPACE
              value: ai-devops
            - name: DASHBOARD_CACHE_TTL_SECONDS
              value: "15"
            - name: DASHBOARD_TIMEOUT_SECONDS
              value: "4"
            - name: REDIS_HOST
              value: redis-master.redis.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_SOCKET_TIMEOUT_SECONDS
              value: "1"
            - name: PROMETHEUS_URL
              value: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
            - name: PROMETHEUS_TIMEOUT_SECONDS
              value: "2"
            - name: KUBERNETES_REQUEST_TIMEOUT_SECONDS
              value: "3"

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
